 version: "3"

 services:
   db:
     image: postgres
     environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
   web:
     build: .
     command: python manage.py runserver 0.0.0.0:8000
     volumes:
       - .:/code
     ports:
       - "8000:8000"
     depends_on:
       - db


#version: '3'
#
#services:
#    python:
#        image: python:3.6
#        volumes:
#            - ./MobileWallet2020:/walletcore
#        ports:
#            - 8000:8000
#        command: bash -c "cd walletcore && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"