# Generated by Django 2.2 on 2021-02-16 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('age', models.CharField(blank=True, choices=[('18-24', 'Eighteen to twenty four'), ('25-34', 'Twenty five to thirty four'), ('35-44', 'Thirty five to forty four'), ('45-54', 'Forty five to fifty four'), ('55-64', 'Fifty five to sixty four'), ('65+', 'Above sixty five')], max_length=8, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
