# Generated by Django 2.2 on 2021-02-17 20:30

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='A name for this account', max_length=100)),
                ('description', models.TextField(help_text='A brief description of this account')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('status', models.CharField(default='Open', max_length=32)),
                ('can_be_overdrawn', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='A name for this wallet', max_length=124)),
                ('description', models.TextField(help_text='A description for this wallet')),
                ('type', models.CharField(choices=[('savings', 'savings'), ('current', 'current')], default='current', max_length=10)),
                ('wallet_pin', models.CharField(blank=True, max_length=128, null=True)),
                ('wallet_otp', models.CharField(blank=True, max_length=128, null=True)),
                ('wallet_pin_created', models.DateTimeField(auto_now=True, null=True)),
                ('wallet_otp_created', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Wallet owner', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('message', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount transfered', max_digits=8)),
                ('reference', models.CharField(max_length=128, null=True)),
                ('transaction_reversed', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_account', to='wallet.Account')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_account', to='wallet.Account')),
            ],
            options={
                'verbose_name_plural': 'Transfers',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(help_text='The wallet this account is related to', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='wallet.Wallet'),
        ),
    ]
