# Generated by Django 2.2 on 2021-02-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='wallet',
            field=models.OneToOneField(help_text='The wallet this account is related to', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='wallet.Wallet'),
        ),
    ]
