# Generated by Django 2.2 on 2021-02-21 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(help_text='The wallet this account is related to', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='wallet.Wallet'),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='description',
            field=models.TextField(help_text='An optional "memo" field for this transaction.'),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='wallet.Transfer'),
        ),
    ]
